DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS LISTAS_DE_TAREFAS;
DROP TABLE IF EXISTS TAREFAS;

CREATE TABLE USUARIOS (
    Id_Usuario INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    senha TEXT NOT NULL
);

CREATE TABLE LISTAS_DE_TAREFAS (
    Id_lista INTEGER PRIMARY KEY  AUTOINCREMENT,
    nome TEXT NOT NULL,
    Id_Usuario INTEGER NOT NULL,
    FOREIGN KEY (Id_Usuario) REFERENCES USUARIOS(Id_Usuario)
);

CREATE TABLE TAREFAS (
    id_tarefa INTEGER PRIMARY KEY AUTOINCREMENT,
    descricao TEXT NOT NULL,
    concluida BOOLEAN NOT NULL DEFAULT FALSE,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_conclusao TIMESTAMP NULL,
    Id_lista INTEGER NOT NULL,
    FOREIGN KEY (Id_lista) REFERENCES LISTAS_DE_TAREFAS(Id_lista)
);



-- Obs: Cadastre de baixo para cima, ordem de precedência